name: Deploy static
description: Deploy a static site

inputs:
  netlify_token:
    description: Netlify auth token
    required: true
  dir:
    description: "Dir to deploy"
    required: false
    default: "."
  cloudflare_token:
    description: "Cloudflare token"
    required: false
  domain:
    description: If using a custom domain
    required: false

runs:
  using: "composite"
  steps:
    - name: Deploy
      id: deploy
      uses: medvesek/github-actions/actions/netlify-deploy@master
      with:
        token: ${{ inputs.netlify_token }}
        dir: ${{ inputs.dir }}
        custom_domain: ${{ inputs.domain }}
    - name: DNS
      uses: medvesek/github-actions/actions/cloudflare-dns@master
      with:
        token: ${{ inputs.cloudflare_token }}
        type: "CNAME"
        name: ${{ inputs.domain }}
        content: ${{ steps.deploy.outputs.default_domain }}
