name: Build

on:
  push:
  workflow_dispatch:
jobs:
  build:
    name: Build actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/build-js-action
        with:
          dir: actions/cloudflare-dns
      - uses: ./.github/actions/build-js-action
        with:
          dir: actions/netlify-deploy
